### ISSUE TITLE
Got Exception has occurred: ModuleNotFoundError No module named 'perspective' error

### ISSUE THREAD

**Issue by XRHTech** [Conway/perspective#11]
Tried to use perspective API wrapper for python but it seems that its not working

**Comment by lbozarth** [comment]
same, did you figure out the solution?

**Comment by FoxGames01** [comment]
same here, dont work to me :(

**Comment by Conway** [comment]
These issues should be fixed in v1.0.3

https://pypi.org/project/perspective/1.0.3/
