### ISSUE TITLE
Mistakes in README

### ISSUE THREAD

**Issue by aflah02** [Conway/perspective#15]
**Describe the bug**
```
from perspective import PerspectiveAPI
p = Perspective("API_KEY")
result = p.score("This is a comment")
print("Toxicity score: " + result["TOXICITY"])
```
In this code PerspectiveAPI should be there in place of Perspective and result["TOXICITY"] throws an error rather using something like a comma could fix this

**Comment by Conway** [comment]
Thank you for catching this, it's been merged.

**Comment by aflah02** [comment]
Cool what plans do you have with this package?
