### ISSUE TITLE
Library is not installing with PIP

### ISSUE THREAD

**Issue by redditindia** [Conway/perspective#7]
C:\Python27\Scripts>pip install perspective
Collecting perspective
  Downloading perspective-0.1b0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\XYZZY\appdata\local\temp\pip-build-fckcbd\perspective\setu
p.py", line 6, in <module>
        with open(path.join(here, 'README.md'), encoding='utf-8') as f:
      File "c:\python27\lib\codecs.py", line 896, in open
        file = __builtin__.open(filename, mode, buffering)
    IOError: [Errno 2] No such file or directory: 'c:\\users\\sdatar\\appdata\\l
ocal\\temp\\pip-build-fckcbd\\perspective\\README.md'

Same can be seen on Heroky

**Comment by Conway** [comment]
A new version of `perspective` was pushed to PYPI today, hopefully this should fix any issues you were encountering. If not, reply here and I'll reopen the issue.
