### ISSUE TITLE
ImportError: cannot import name 'Perspective'

### ISSUE THREAD

**Issue by amittos** [Conway/perspective#9]
Thank you for creating this wrapper. 

I'm experiencing a weird problem. Even though the python package `perspective` is definitely installed on my system, when I'm running the script I get the following error: 

`ImportError: cannot import name 'Perspective'`

Any ideas? I don't have this problem with any of my other packages.

**Comment by hkyq** [comment]
Same here. Installed with `pip3 install perspective`.

**Comment by kasavin** [comment]
I'm seeing this as well. Tried changing the package install path but that didn't work.

**Comment by annabananas8712** [comment]
When you pip install the package as stated in the directions, you are only downloading the perspective-0.1b0-py3.6.egg-info file with information on the package.  The perspective file on this project contains all of the .py files for the module, of which you have to make the package folder on your own in dist-packages or site-packages in your python lib folder

**Comment by Nithindanday** [comment]
so that means the docs should be updated

**Comment by isigebengu-mikey** [comment]
why doesn't he just make __init__.py

**Comment by NURA100NURA100** [comment]
Same This happenening with me I also found that there is not modulto import from there is only the information or text files as isigebengu-mikey said. Hope the Devs fix this quick as i am really looking forward to using this
![image_2021-02-19_120406](https://user-images.githubusercontent.com/73468768/108467018-91241580-72aa-11eb-8c59-0b5901204454.png)
![image](https://user-images.githubusercontent.com/73468768/108467081-a436e580-72aa-11eb-8226-71a390c4a0e2.png)

**Comment by NURA100NURA100** [comment]
> Same This happenening with me I also found that there is not modulto import from there is only the information or text files as isigebengu-mikey said. Hope the Devs fix this quick as i am really looking forward to using this
> ![image_2021-02-19_120406](https://user-images.githubusercontent.com/73468768/108467018-91241580-72aa-11eb-8c59-0b5901204454.png)
> ![image](https://user-images.githubusercontent.com/73468768/108467081-a436e580-72aa-11eb-8226-71a390c4a0e2.png)

Well I found a wrok around, download the files from github. it works but the thing is that you will need to keep it in you rproject folder

**Comment by HexyeDEV** [comment]
How could i use the library? It doesn't work even after installation

**Comment by Conway** [comment]
These issues should be fixed in v1.0.3

https://pypi.org/project/perspective/1.0.3/

**Comment by Sarayu99** [comment]
how can I print scores other than TOXICITY in v1.0.3? WHen I use the below code and print 'results' it is a dictionary with only one key - 'TOXICITY'


from perspective import PerspectiveAPI
p = Perspective("API_KEY")
result = p.score("This is a comment")
print("Toxicity score: " + result["TOXICITY"])
